[build]
command = "cd backend && pip install --upgrade pip && pip install -r requirements.txt"

[run]
command = "cd backend && gunicorn -c gunicorn_config.py wsgi:app"

[env]
PORT = "5002"

[apt]
packages = ["python3-dev", "gcc", "g++", "libffi-dev", "libssl-dev", "build-essential"]